apiVersion: v2
name: sonarqube
description: A Helm chart for deploying SonarQube.
type: application
version: 1.3.0
appVersion: 8.7.1
keywords:
  - sonarqube
  - sast
  - analysis
  - security
  - code
  - coverage
  - quality
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
sources:
  - https://github.com/SonarSource/sonarqube
  - https://github.com/SonarSource/docker-sonarqube
maintainers:
  - name: jordiprats
    email: jordi.prats@gmail.com
annotations:
  artifacthub.io/changes: |
    - Added support for sonarqube 7.9 LTS
